/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SonguploadImport } from './routes/song_upload'
import { Route as AuthorcreateImport } from './routes/author_create'

// Create/Update Routes

const SonguploadRoute = SonguploadImport.update({
  path: '/song_upload',
  getParentRoute: () => rootRoute,
} as any)

const AuthorcreateRoute = AuthorcreateImport.update({
  path: '/author_create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/author_create': {
      id: '/author_create'
      path: '/author_create'
      fullPath: '/author_create'
      preLoaderRoute: typeof AuthorcreateImport
      parentRoute: typeof rootRoute
    }
    '/song_upload': {
      id: '/song_upload'
      path: '/song_upload'
      fullPath: '/song_upload'
      preLoaderRoute: typeof SonguploadImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthorcreateRoute,
  SonguploadRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/author_create",
        "/song_upload"
      ]
    },
    "/author_create": {
      "filePath": "author_create.tsx"
    },
    "/song_upload": {
      "filePath": "song_upload.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
